---
- name: Enable Apache modules
  command: >
    a2enmod {{ item }}
  with_items: apache_mods_enabled
  register: command_result
  changed_when: >
    "To activate the new configuration, you need to run:" in command_result.stdout
  notify: restart apache

- name: Disable Apache modules
  command: >
    a2dismod {{ item }}
  with_items: apache_mods_disabled
  register: command_result
  changed_when: >
    "To activate the new configuration, you need to run:" in command_result.stdout
  notify: restart apache
